export const HABITS_FETCHED = 'HABITS_FETCHED';
export const HABITS_LOADING = 'HABITS_LOADING';
export const HABITS_ERROR = 'HABITS_ERROR';
export const HABITS_REQUESTED = 'HABITS_REQUESTED';


export const SHOW_INPUT = 'SHOW_INPUT';
export const HIDE_INPUT = 'HIDE_INPUT';
export const REMOVE_HABIT = 'REMOVE_HABIT';
export const MAKE_EDIT_HABIT = 'MAKE_EDIT_HABIT';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const FETCH_CATEGORIES_HIDE = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';