export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGIN_SAGA = "LOGIN_SAGA";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const HABITS_FETCHED = 'HABITS_FETCHED';
export const HABITS_LOADING = 'HABITS_LOADING';
export const HABITS_ERROR = 'HABITS_ERROR';
export const HABITS_REQUESTED_SAGA = 'HABITS_REQUESTED_SAGA';

export const HABIT_REMOVE_SAGA = 'HABIT_REMOVE_SAGA';
export const HABIT_REMOVE_LOADING = 'HABIT_REMOVE_LOADING';
export const HABIT_REMOVED = 'HABIT_REMOVED';
export const HABIT_REMOVE_ERROR = 'HABIT_REMOVE_ERROR';

export const HABIT_EDIT_SHOW = 'HABIT_EDIT_SHOW';
export const HABIT_EDIT_HIDE = 'HABIT_EDIT_HIDE';
export const HABIT_CREATE_SAGA = 'HABIT_CREATE_SAGA';
export const HABIT_UPDATE_SAGA = 'HABIT_UPDATE_SAGA';
export const HABIT_UPDATED = 'HABIT_UPDATED';
export const HABIT_CREATED = 'HABIT_CREATED';
export const HABIT_UPDATE_LOADING = 'HABIT_UPDATE_LOADING';
export const HABIT_UPDATE_ERROR = 'HABIT_UPDATE_ERROR';

export const HABIT_DONE_SAGA = 'HABIT_DONE_SAGA';
export const HABIT_DONE = 'HABIT_DONE';
export const HABIT_DONE_ERROR = 'HABIT_DONE_ERROR';

export const HABIT_DONE_SHOW_ALERT = 'HABIT_DONE_SHOW_ALERT';
export const HABIT_DONE_HIDE_ALERT = 'HABIT_DONE_HIDE_ALERT';


export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const CATEGORIES_REQUESTED_SAGA = 'CATEGORIES_REQUESTED_SAGA';
export const CATEGORY_CREATE_SAGA = 'CATEGORY_CREATE_SAGA';
export const CATEGORY_CREATED = 'CATEGORY_CREATED';

export const STATISTICS_LOADING = 'STATISTICS_LOADING';
export const STATISTICS_LOADED = 'STATISTICS_LOADED';



