export const HABITS_FETCHED = 'HABITS_FETCHED';
export const HABITS_LOADING = 'HABITS_LOADING';
export const HABITS_ERROR = 'HABITS_ERROR';
export const HABITS_REQUESTED = 'HABITS_REQUESTED';

export const HABIT_REMOVE = 'HABIT_REMOVE';
export const HABIT_EDIT_SHOW = 'HABIT_EDIT_SHOW';
export const HABIT_EDIT_HIDE = 'HABIT_EDIT_HIDE';
export const HABIT_CREATE = 'HABIT_CREATE';
export const HABIT_UPDATE = 'HABIT_UPDATE';

export const FETCH_CATEGORIES_HIDE = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';